ProgrammingProject/ProgrammingProject/Areas/Administration/Models/Section/Section.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using ProgrammingProject.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProgrammingProject.Areas.Administration.Models.Section
{
    public class Section
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public SelectList Restaurants { get; set; }
        public int RestaurantId { get; set; }
    }
}

ProgrammingProject/ProgrammingProject/Areas/Member/Models/Account/Create.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ProgrammingProject.Areas.Member.Models.Account
{
    public class Create
    {
        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string PhoneNumber { get; set; }

        [Display(Name = "Title")]
        public int TitleId { get; set; }

        public SelectList Titles { get; set; }

        [Display(Name = "Email")]
        public string Email { get; set; }


        [DataType(DataType.Password), Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password), Display(Name = "Confirm Password")]
        public string ConfirmPassword { get; set; }

    }
}

ProgrammingProject/ProgrammingProject/Areas/Administration/Controllers/SectionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProgrammingProject.Areas.Administration.Models.Section;
using ProgrammingProject.Data;

namespace ProgrammingProject.Areas.Administration.Controllers
{
    public class SectionController : AdministrationBaseController
    {
        public SectionController(ApplicationDbContext context, IMapper mapper, UserManager<IdentityUser> userManager) : base(context, mapper, userManager)
        {

        }
        public async Task<IActionResult> Index()
        {
            var sections = await _context.Sections.ToListAsync();
            return View(sections);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var r = new Models.Section.Section
            {
                Restaurants = new SelectList(await _context.Restaurants.ToListAsync(), "Id", "Name")
            };
            return View(r);
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Name", "RestaurantId")] Models.Section.Section s)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var section = new Data.Section
                    {
                        Name = s.Name,
                        RestaurantId = s.RestaurantId
                    };
                    _context.Sections.Add(section);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception)
                {
                    ModelState.AddModelError("Exception", "Oops! There was an Error!");
                }
            }
            s.Restaurants = new SelectList(await _context.Restaurants.ToListAsync(), "Id", "Name");
            return View(s);
        }
        public async Task<IActionResult> Delete([Bind("Id", "Name", "RestaurantId")] Data.Section s)
        {
            var section = await _context.Sections.FirstOrDefaultAsync(m=>m.Id == s.Id);
             _context.Sections.Remove(section);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit([Bind("Id", "Name", "RestaurantId")] Data.Section s)
        {

            var section = await _context.Sections.FirstOrDefaultAsync(m => m.Id == s.Id);
            Models.Section.Section modelSection = new Models.Section.Section
            {
                Id = section.Id,
                Name = section.Name,
                Restaurants = new SelectList(await _context.Restaurants.ToListAsync(), "Id", "Name")
            };
            return View(modelSection);
        }

        [HttpPost]
        public async Task<IActionResult> Edit([Bind("Id", "Name", "RestaurantId")] Models.Section.Section s)
        {
            if (ModelState.IsValid)
            {
                if(s.RestaurantId == 0)
                {

                }
                try
                {
                    var m = new Data.Section
                    {
                        Id = s.Id,
                        Name = s.Name,
                        RestaurantId = s.RestaurantId
                    };
                    _context.Sections.Update(m);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception)
                {
                    ModelState.AddModelError("Exception", "Oops there was an error");
                }
            }
            s.Restaurants = new SelectList(await _context.Restaurants.ToListAsync(), "Id", "Name", s.RestaurantId);
            return View(s);

        }
    }
}

ProgrammingProject/ProgrammingProject/Areas/Administration/Views/Section/Create.cshtml
@model ProgrammingProject.Areas.Administration.Models.Section.Section

<div class="row text-white">
    <div class="col-6 w-100 p-4" style="display: inline-block; background-color: rgba(0,0,0, 0.95); border-radius: 15px;   color: #f1f1f1; ">
        <form>
            <div class="form-group m-0">
                <label asp-for="@Model.RestaurantId">Restaurants:</label>
                <select class="form-control mb-3" style="border-radius: 5px; height: 35px; padding: 0.375px; border: 1px solid;" asp-for="@Model.RestaurantId" asp-items="@Model.Restaurants">
                    <option value="">Select a Restaurant</option>
                </select>
            </div>
            <div class="form-group m-0">
                <label asp-for="@Model.Name">Section Name:</label>
                <input class="form-control mb-4" type="text" asp-for="@Model.Name" />
            </div>
            <input type="submit" formmethod="post" asp-area="Administration" asp-controller="Section" asp-action="Create" />
        </form>
    </div>
</div>

ProgrammingProject/ProgrammingProject/Areas/Administration/Views/Section/Edit.cshtml
@model ProgrammingProject.Areas.Administration.Models.Section.Section
    <div class="row text-white">
        <div class="col-md-6 p-1 m-0" style="display: inline-block; background-color: rgba(0,0,0, 0.95); border-radius: 15px;   color: #f1f1f1; ">
            <form>
                <label asp-for="@Model.Name">Name</label>
                <input type="text" value="@Model.Name" asp-for="@Model.Name" />

                <label asp-for="@Model.RestaurantId">Restaurants</label>
                <select asp-for="@Model.RestaurantId" asp-items="@Model.Restaurants">
                    <option value="">Choose a Restaurant</option>
                </select>
                <span class="text-danger" asp-validation-for="@Model.RestaurantId">*</span>
                <br /> <br />
                <input type="submit" asp-area="Administration" asp-controller="Section" asp-action="Edit" formmethod="post" value="Save Changes" />
            </form>
        </div>
    </div>

ProgrammingProject/ProgrammingProject/Areas/Administration/Views/Section/Index.cshtml
@model IReadOnlyCollection<ProgrammingProject.Data.Section>

<div class="row text-white">
    <div class="p-1 m-0" style="display: inline-block; background-color: rgba(0,0,0, 0.95); border-radius: 15px;   color: #f1f1f1; ">
        <h2 class="text-uppercase m-2 p-2"><a asp-area="Administration" asp-controller="Section" asp-action="Create">Create An Area</a></h2>
        <div class="p-3">
            <table>
                <thead>
                    <tr>
                        <td class="font-weight-bold pr-5 pb-3">Area Id</td>
                        <td class="font-weight-bold pr-5 pb-3">Name</td>
                        <td class="font-weight-bold pr-5 pb-3">Management</td> 
                    </tr>
                </thead>
                <tbody>
                    @foreach (var m in Model)
                    {
                        <tr>
                            <td class="pl-4 pb-3">@m.Id</td>
                            <td class="pb-3">@m.Name</td>
                            <td class="pr-5 pb-3"><a class="text-secondary" asp-area="Administration" asp-controller="Table" asp-action="Index" asp-route-id="@m.Id">Manage Section Tables</a></td>
                            <td class="pr-5 pb-3"><a class="text-secondary" asp-area="Administration" asp-controller="Section" asp-action="Edit" asp-route-id="@m.Id">Edit</a></td>
                            <td class="pb-3"><a class="text-secondary" asp-area="Administration" asp-controller="Section" asp-action="Delete" asp-route-id="@m.Id">Delete</a></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>